rm -r ./ShaderGen/.gitignore
rm -r ./Mesh-Skeleton-Tool/.git
rm -r ./shader-school/.gitignore
rm -r ./shader-school/.git
rm -r ./F1/Example42/.gitignore
rm -r ./F1/Example16/.gitignore
rm -r ./F1/Example17/.gitignore
rm -r ./F1/Example31/.gitignore
rm -r ./F1/Example30/.gitignore
rm -r ./F1/Example28/.gitignore
rm -r ./F1/Example09/.gitignore
rm -r ./F1/Example11/.gitignore
rm -r ./F1/Example34/.gitignore
rm -r ./F1/Example39/.gitignore
rm -r ./F1/Example01/.gitignore
rm -r ./F1/GLUS/.gitignore
rm -r ./F1/Example03/.gitignore
rm -r ./F1/Example06/.gitignore
rm -r ./F1/Example40/.gitignore
rm -r ./F1/Example15/.gitignore
rm -r ./F1/Example18/.gitignore
rm -r ./F1/Example41/.gitignore
rm -r ./F1/Example08/.gitignore
rm -r ./F1/Example07/.gitignore
rm -r ./F1/Example24/.gitignore
rm -r ./F1/Example27/.gitignore
rm -r ./F1/Example21/.gitignore
rm -r ./F1/Example35/.gitignore
rm -r ./F1/Example20/.gitignore
rm -r ./F1/Example32/.gitignore
rm -r ./F1/Example13/.gitignore
rm -r ./F1/Example10/.gitignore
rm -r ./F1/Example38/.gitignore
rm -r ./F1/Example05/.gitignore
rm -r ./F1/Example23/.gitignore
rm -r ./F1/Example14/.gitignore
rm -r ./F1/Example12/.gitignore
rm -r ./F1/Example26/.gitignore
rm -r ./F1/Example19/.gitignore
rm -r ./F1/Example37/.gitignore
rm -r ./F1/Example43/.gitignore
rm -r ./F1/Example36/.gitignore
rm -r ./F1/Example02/.gitignore
rm -r ./F1/Example22/.gitignore
rm -r ./F1/Example33/.gitignore
rm -r ./F1/Example44/.gitignore
rm -r ./F1/Example25/.gitignore
rm -r ./F1/Example45/.gitignore
rm -r ./F1/Example04/.gitignore
rm -r ./F1/Example29/.gitignore
rm -r ./Learning_OpenGL/.gitignore
rm -r ./Learning_OpenGL/.git
