image: Visual Studio 2017

branches:
  only:
    - master

init:
  - set QTDIR=C:\Qt\5.9.5\msvc2017_64
  - call "%QTDIR%\bin\qtenv2.bat"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd /D "%APPVEYOR_BUILD_FOLDER%"

install:
  - choco install nsis
  - set PATH=%PATH%;"C:\Program Files (x86)\NSIS"

build_script:
  - mkdir -p build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=installed ..
  - cmake --build . --config Release --target install
  - cpack -G NSIS64

artifacts:
  - path: build\ShaderGen-*.exe
