language: cpp

branches:
  only:
    - master

matrix:
  include:
  - compiler: gcc
    os: linux
    dist: trusty
  - compiler: clang
    os: osx
    env: MACOSX_DEPLOYMENT_TARGET=10.11

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:beineri/opt-qt593-trusty; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" > linuxdeployqt.AppImage; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod a+x linuxdeployqt.AppImage; fi
 - transfer() { curl --progress-bar --upload-file "$1" "https://transfer.sh/$1"; }
install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq qt59base; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt59/bin/qt59-env.sh; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:/usr/local/opt/qt/bin/; fi
 
script:
- mkdir -p build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=installed -DCMAKE_BUILD_TYPE=Release ..
- cmake --build . --config Release --target install
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ../linuxdeployqt.AppImage installed/bin/ShaderGen.desktop -appimage; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv ShaderGen-*.AppImage ShaderGen-linux-x86_64.AppImage; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then transfer ShaderGen*.AppImage; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cpack -G DragNDrop; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then transfer ShaderGen*.dmg; fi
